### ISSUE TITLE
TypeError: Cannot destructure property 'popperId' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by bufgix** [Akryum/floating-vue#924]
I'm migrating from Vue2 to Vue3. I changed the package name `v-tooltip` => `floating-vue` and I just use `v-tooltip` directive so i just register the directive like:

```js
import { VTooltip } from 'floating-vue'
   
//...
app.directive('tooltip', VTooltip)
```

and I'm getting error when I use directive

```js
 <h3 v-tooltip="'test popover'"  v-text="$t('Welcome Back')" />
```

```error
Uncaught (in promise) TypeError: Cannot destructure property 'popperId' of 'undefined' as it is undefined.
```

<img width="615" alt="resim" src="https://user-images.githubusercontent.com/22038798/209941653-0dd86597-3b39-4af3-87d5-f03978fcbec7.png">

Im on the migration process and i use [`@vue/compat`](https://www.npmjs.com/package/@vue/compat) (Migration Build) on Vue 2 mode.

floating-vue version is `^2.0.0-beta.20`

**Comment by junaidshad** [comment]
did you figure out the issue?

**Comment by bufgix** [comment]
> did you figure out the issue?

Nope. I cancelled vue 3 migration still using v-tooltip for vue 2 :( @junaidshad

**Comment by jarooda** [comment]
it looks like we will encounter this error if we use MODE: 2 in @vue/compat
to remove the error, use MODE: 3 in compat cofiguration

```js
import { configureCompat } from 'vue'

...

export default {
  install (app) {
    configureCompat({
      MODE: 3
    })
    app.directive('tooltip', VTooltip)
    app.directive('close-popper', VClosePopper)
  })
}
```

**Comment by junaidshad** [comment]
@jarooda 
For me it didn't work even with MODE: 3.... 
it just worked after i removed the @vue/compat migration build package. Most of the third party dependencies does not support vue compat migration build.

**Comment by vgshenoy** [comment]
Anybody have this working yet? 

Hitting roadblocks on our migration to Vue 3 with this.

Also made a minimal repro at https://stackblitz.com/edit/node-whjkss?file=src/Playground.vue

Hoping someone can point me in the right direction 🙏

**Comment by junaidshad** [comment]
@vgshenoy No, No luck in getting it work under the @vue/compat migration build so far.

**Comment by alecgibson** [comment]
> as a workaround we've been using the vue 2 version of the library

This doesn't work for us; we get this error instead:

```
Cannot read properties of undefined (reading 'theme')
TypeError: Cannot read properties of undefined (reading 'theme')
    at Proxy.eval (webpack-internal:///./node_modules/floating-vue/dist/floating-vue.es.js:226:35)
    at resolvePropValue (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:7298:53)
    at setFullProps (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:7274:20)
    at initProps (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:7097:3)
    at setupComponent (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:10489:3)
    at mountComponent (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:8801:7)
    at processComponent (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:8766:9)
    at patch (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:8254:11)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:8913:11)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/compat/dist/vue.esm-bundler.js:652:19)
```

Presumably because `this` is [no longer defined](https://v3-migration.vuejs.org/breaking-changes/props-default-this.html) in the props default function.

**Comment by alecgibson** [comment]
Okay did some more digging using `vue@3` with `floating-vue@2`.

I don't think this library plays nicely with the compatibility build and the [render function break](https://v3-migration.vuejs.org/breaking-changes/render-function-api.html).

The library works for us if we disable the [`RENDER_FUNCTION`](https://v3-migration.vuejs.org/migration-build.html#compat-configuration) compatibility flag:

```js
import {configureCompat} from 'vue';

configureCompat({
  RENDER_FUNCTION: false,
});
```

**Comment by luisrossi** [comment]
+1

**Comment by omairmir** [comment]
> did you figure out the issue?

hi buddy same error

**Comment by junaidshad** [comment]
@omairmir Hey!
Back then, we discarded this package and switched to vue-tippy plugin (https://www.npmjs.com/package/vue-tippy).

`appContainer.use(VueTippy, {
    directive: 'tooltip',
    arrow: true
})`

This is how it was used. This way we didn't have to change the v-tooltip directive inside vue components.

**Comment by ryanuo** [comment]
vite.config.ts 
```ts
import { defineConfig } from 'vite'

export default defineConfig({
  ssr: {
    noExternal: ['v-tooltip'],
  },
})
```

**Comment by shahsaif99** [comment]
> vite.config.ts
> 
> import { defineConfig } from 'vite'
> 
> export default defineConfig({
>   ssr: {
>     noExternal: ['v-tooltip'],
>   },
> })

Tried this as well its still there
